# Generated by Django 5.2 on 2025-04-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='取引先コード')),
                ('name', models.CharField(max_length=200, verbose_name='仕入先名')),
                ('contact_person', models.CharField(blank=True, default='', max_length=100, verbose_name='担当者名')),
                ('phone', models.CharField(max_length=50, verbose_name='電話番号')),
                ('fax', models.CharField(blank=True, default='', max_length=50, verbose_name='FAX番号')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('postal_code', models.CharField(max_length=10, verbose_name='郵便番号')),
                ('prefecture', models.CharField(max_length=50, verbose_name='都道府県')),
                ('city', models.CharField(max_length=100, verbose_name='市区町村')),
                ('town', models.CharField(max_length=200, verbose_name='町名・番地')),
                ('building', models.CharField(blank=True, default='', max_length=200, verbose_name='建物名・部屋番号')),
                ('website', models.URLField(blank=True, default='', verbose_name='Webサイト')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '仕入先',
                'verbose_name_plural': '仕入先',
            },
        ),
    ]
