# Generated by Django 5.2 on 2025-04-26 01:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_supplier_options_supplier_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='部品名')),
                ('category', models.CharField(choices=[('head', 'ヘッド'), ('shaft', 'シャフト'), ('grip', 'グリップ'), ('other', 'その他')], max_length=50, verbose_name='カテゴリ')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='原価')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='見積用単価')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='現在庫数')),
                ('reorder_level', models.PositiveIntegerField(default=0, verbose_name='補充閾値')),
                ('description', models.TextField(blank=True, default='', verbose_name='備考')),
                ('image', models.ImageField(blank=True, null=True, upload_to='parts/', verbose_name='部品画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_parts', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='masters.supplier', verbose_name='仕入先')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_parts', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '部品',
                'verbose_name_plural': '部品',
                'ordering': ['id'],
            },
        ),
    ]
