# Generated by Django 5.2 on 2025-05-04 00:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='税率(%)'),
        ),
    ]
